name: Deploy with Maven

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Build and deploy
      run: mvn deploy -B
      env:
        MAVEN_USERNAME: CiroZDP
        MAVEN_PASSWORD: ${{ secrets.SECRET_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}

