name: Deploy with Maven

on:
  push:
    branches:
      - master  

jobs:
  deploy:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Download JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Deploy to Github Package Registry
        env:
          MAVEN_USERNAME: CiroZDP
          MAVEN_PASSWORD: ${{ secrets.SECRET_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          mkdir -p ~/.m2
          printf "<settings><servers><server><id>github</id><username>CiroZDP</username><password>${{ secrets.SECRET_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy